spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/baoss-db
    username: postgres
    password: Aposuv74

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
    #appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka
    fetchRegistry: true
    registerWithEureka: true
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:5555/user-service/auth/user
