FROM maven AS MAVEN_BUILD
COPY src /home/order-service/src
COPY pom.xml /home/order-service
RUN mvn -f /home/order-service/pom.xml clean package -DprofileActive=dev-docker -U

FROM openjdk
COPY --from=MAVEN_BUILD /home/order-service/target/order-service-0.0.1.jar /usr/local/lib/order-service.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/usr/local/lib/order-service.jar", "--spring.profiles.active=dev-docker"]
