spring:
  application:
    name: order-service
  jpa:
    database: POSTGRESQL
#    generate-ddl: true
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        event:
#          merge:
#            entity_copy_observer: allow

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/baoss_db
    username: postgres
    password: Aposuv74

#  rabbitmq:
#    username: "guest"
#    password: "guest"

server:
  port: 8081
  error:
    include-message: always

eureka:
  instance:
    preferIpAddress: true
    #appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone:  http://eureka-server:8080/eureka
    fetchRegistry: true
    registerWithEureka: true

baoss:
  orders:
    clean-install: ${CLEAN_INSTALL:false}
    number-of-users-for-generation: ${USER_NUMBER_GENERATION:500}

tb-api:
  url: "http://tb-api:5555"
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:5555/user-service/auth/user
