spring:
  application:
    name: billing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/baoss_db
    username: postgres
    password: Aposuv74

server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
    #appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone:  http://eureka-server:8080/eureka
    fetchRegistry: true
    registerWithEureka: true

baoss:
  billing:
    number-of-users-for-generation: ${USER_NUMBER_GENERATION:500}

tb-api:
  url: "http://tb-api:5555"
