FROM maven AS MAVEN_BUILD
COPY src /home/user-service/src
COPY pom.xml /home/user-service
RUN mvn -f /home/user-service/pom.xml clean package -DprofileActive=dev-docker -U

FROM openjdk
COPY --from=MAVEN_BUILD /home/user-service/target/user-service-0.0.1.jar /usr/local/lib/user-service.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/usr/local/lib/user-service.jar", "--spring.profiles.active=dev-docker"]