spring:
  application:
    name: eureka-server

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false     # Don’t register with Eureka service.
    fetchRegistry: false          # Don’t cache registry information locally.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
