FROM maven AS MAVEN_BUILD
COPY src /home/tb-api/src
COPY pom.xml /home/tb-api
RUN mvn -f /home/tb-api/pom.xml clean package -DprofileActive=dev-docker -U

FROM openjdk
COPY --from=MAVEN_BUILD /home/tb-api/target/tb-api-0.0.1.jar /usr/local/lib/tb-api.jar
EXPOSE 5555
ENTRYPOINT ["java", "-jar", "/usr/local/lib/tb-api.jar", "--spring.profiles.active=dev-docker"]
