FROM maven AS MAVEN_BUILD
COPY src /home/offer-service/src
COPY pom.xml /home/offer-service
RUN mvn -f /home/offer-service/pom.xml clean package -DprofileActive=prod -U

FROM openjdk
COPY --from=MAVEN_BUILD /home/offer-service/target/offer-service-0.0.1.jar /usr/local/lib/offer-service.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "/usr/local/lib/offer-service.jar", "--spring.profiles.active=prod"]
