spring:
  application:
    name: tb-api

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
    #appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    fetchRegistry: true
    registerWithEureka: true

#zuul:
#  routes:
#    user-service:
#      path: /user-service/**
#      serviceId: user-service
#    order-service:
#      path: /order-service/**
#      serviceId: order-service
