spring:
  application:
    name: order-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/baoss-db
    username: postgres
    password: 123456
  rabbitmq:
    username: "guest"
    password: "guest"

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
    #appname: ${spring.application.name}  # ==> This is a instance of ABC-SERVICE
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka
    fetchRegistry: true
    registerWithEureka: true

#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:5555/user-service/auth/user
