FROM maven:3.8.6-openjdk-18 AS MAVEN_BUILD
COPY src /home/billing-service/src
COPY pom.xml /home/billing-service
RUN mvn -f /home/billing-service/pom.xml clean package -DprofileActive=dev-docker -U

FROM openjdk
COPY --from=MAVEN_BUILD /home/billing-service/target/billing-service-0.0.1.jar /usr/local/lib/billing-service.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "/usr/local/lib/billing-service.jar", "--spring.profiles.active=dev-docker"]
